name: NPM Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: true

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 21.x
          cache: "pnpm"

      - name: Build and package the extension into a zip artifact 
        run: pnpm package:chrome
